verbosity: false
img_size_pixel: 512
resolution: 0.2
checkpoint: ${oc.env:HOME}/dev/cosia-detection/checkpoint/ckpt-epoch=57-val_loss=0.60_1_FLAIR-HF_12_scaling_RVBIE_unetresnet34.ckpt
n_classes: 19
batch_size: 2
# key_path: ['state_dict']
use_gpu: false
output_path: ${oc.env:HOME}/dev/cosia-detection/output/argmax
interruption_recovery: False
mutual_exclusion: True
model_name: 'unet'
# model_prefix: 'model.seg_model'
encoder_name: 'resnet34'
output_type: "uint8"
sparse_mode: False
threshold: 0.5
num_worker: 0
num_thread: 16
zone:
  tile_factor: 1
  margin: 10
  output_dalle_size: 2500
  layers:
    - path: ${oc.env:HOME}/dev/cosia-detection/data/rasters/D012_2019-Z11_UU-ortho_img.tif
      key: rvbie
      name: rvbie
      bands: [1, 2, 3, 4, 5]
  extent: ${oc.env:HOME}/dev/cosia-detection/data/zone_test-shape-flair-detect.shp
