#### DATA PATHS
paths:
    out_folder : ''
    out_model_name: ''

    ######## TRAIN NEEDED 
    train_csv : '/csv_toy/flair-1-paths-toy-train_ag.csv'
    val_csv   : '/csv_toy/flair-1-paths-toy-val_ag.csv'
    ######## PREDICT (PATCH) NEEDED
    test_csv : ''
    ckpt_model_path: ""

    path_metadata_aerial: '../flair_aerial_metadata.json' 


#### USAGE
tasks:
    train: False
    train_tasks: 
        init_weights_only_from_ckpt: False
        resume_training_from_ckpt: False

    predict: True

    metrics: True
    delete_preds: True

#### TRAINING CONF
model_framework: 
    model_provider: HuggingFace
    HuggingFace:
        org_model: openmmlab/upernet-swin-small
    SegmentationModelsPytorch:
        encoder_decoder:
        
use_augmentation: True
use_metadata: False # Can be True if FLAIR dataset

channels: [1,2,3,4,5] # starts at 1
norm_type: custom # [scaling, custom, without], default: scaling to range [0,1], see github readme
norm_means: [105.08,110.87,101.82,106.38,53.26] # same length (order) as channels
norm_stds: [52.17,45.38,44,39.69,79.3] # same length (order) as channels

seed: 2022

#### HYPERPARAMETERS
batch_size: 5
learning_rate: 0.02
num_epochs: 3

#### DATA CONF
use_weights: True
classes: # k = value in MSK : v = [weight, name]
    1:  [1, 'building']
    2:  [1, 'pervious surface']
    3:  [1, 'impervious surface']
    4:  [1, 'bare soil']
    5:  [1, 'water']
    6:  [1, 'coniferous']
    7:  [1, 'deciduous']
    8:  [1, 'brushwood']
    9:  [1, 'vineyard']
    10: [1, 'herbaceous vegetation']
    11: [1, 'agricultural land']
    12: [1, 'plowed land']
    13: [1, 'swimming_pool']
    14: [1, 'snow']
    15: [0, 'clear cut']
    16: [0, 'mixed']
    17: [0, 'ligneous']
    18: [1, 'greenhouse']
    19: [0, 'other']

#### PREDICT CONF
georeferencing_output : True

#### COMPUTATIONAL RESSOURCES
accelerator: gpu # or cpu
num_nodes: 1
gpus_per_node: 1
strategy: 'auto' # null if only one GPU, else 'ddp' 
num_workers: 10

#### CKPT OPTIONS 
ckpt_save_also_last: True
ckpt_verbose: False
ckpt_weights_only: False
ckpt_monitor: val_loss
ckpt_monitor_mode: min
ckpt_earlystopping_patience: 30

#### PRINT PROGRESS
cp_csv_and_conf_to_output: True
enable_progress_bar: True
progress_rate: 10
